/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const localUrl = `http://localhost:8000`
export const projectId = "pnwbgkpowxmwsjozgyft"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBud2Jna3Bvd3htd3Nqb3pneWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3ODc0ODYsImV4cCI6MjA4NjM2MzQ4Nn0.c5Z3_8FBP3I9yFXDufXfnVLd_EegAyRRn1p_UDXcUWQ"